/**
 * Injection tokens
 */
export const CONFIGURATION_SERVICE_TOKEN = Symbol('CONFIG_SERVICE');
export const CONFIGURATION_TOKEN = 'CONFIGURATION_TOKEN';
export const CONFIGURATION_KEY = 'CONFIGURATION_KEY';
export const CONFIGURATION_CONTENT_INITIALIZATION =
  'CONFIGURATION_CONTENT_INITIALIZATION';
export const CONFIGURATION_LOADER = 'CONFIGURATION_LOADER';

export const PARTIAL_CONFIGURATION_KEY = 'PARTIAL_CONFIGURATION_KEY';
export const PARTIAL_CONFIGURATION_PROPNAME = 'KEY';
