/**
 * Injection tokens
 */
export const CONFIGURATION_SERVICE_TOKEN = Symbol('CONFIG_SERVICE');
export const CONFIGURATION_TOKEN = Symbol('CONFIGURATION_TOKEN');
export const VALIDATED_CONFIGURATION_KEY = 'CONFIGURATION_KEY';
export const VALIDATED_CONFIGURATION_TOKEN = Symbol(
  'VALIDATED_CONFIGURATION_TOKEN',
);
export const CONFIGURATION_CONTENT_INITIALIZATION = Symbol(
  'CONFIGURATION_CONTENT_INITIALIZATION',
);
export const CONFIGURATION_LOADER = Symbol('CONFIGURATION_LOADER');

export const PARTIAL_CONFIGURATION_KEY = 'PARTIAL_CONFIGURATION_KEY';
export const PARTIAL_CONFIGURATION_PROPNAME = 'KEY';
